apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-webpage
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-webpage
  template:
    metadata:
      labels:
        app: my-webpage
    spec:
      containers:
      - name: nginx
        image: veerareddy1422/ecomm
        ports:
        - containerPort: 80
